In [44]:
import tensorflow as tf
tf.test.gpu_device_name()

'/device:GPU:0'

In [2]:
device = "cuda"

In [3]:
!pip install -q kaggle



In [4]:
#@title
!mkdir ~/.kaggle

In [5]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"daveishasnehalbhai","key":"f9f97e7cbfbd655e595775bf2e9113e6"}'}

In [6]:
! cp kaggle.json ~/.kaggle/

In [7]:
! chmod 600 ~/.kaggle/kaggle.json

In [8]:
! kaggle datasets download -d behrad3d/nasa-cmaps

 97% 12.0M/12.3M [00:01<00:00, 14.0MB/s]
100% 12.3M/12.3M [00:01<00:00, 7.50MB/s]


In [9]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [10]:
import zipfile

In [11]:
with zipfile.ZipFile("/content/nasa-cmaps.zip","r") as z:
    z.extractall(".")

In [45]:
import pandas as pd
data_train = pd.read_csv('/content/CMaps/train_FD001.txt',sep=' ',header=None)
data_test = pd.read_csv('/content/CMaps/test_FD001.txt',sep=' ',header=None)

In [46]:
data_train
data_test

0    1       2       3      4       5       6        7        8   \
0        1    1  0.0023  0.0003  100.0  518.67  643.02  1585.29  1398.21   
1        1    2 -0.0027 -0.0003  100.0  518.67  641.71  1588.45  1395.42   
2        1    3  0.0003  0.0001  100.0  518.67  642.46  1586.94  1401.34   
3        1    4  0.0042  0.0000  100.0  518.67  642.44  1584.12  1406.42   
4        1    5  0.0014  0.0000  100.0  518.67  642.51  1587.19  1401.92   
...    ...  ...     ...     ...    ...     ...     ...      ...      ...   
13091  100  194  0.0049  0.0000  100.0  518.67  643.24  1599.45  1415.79   
13092  100  195 -0.0011 -0.0001  100.0  518.67  643.22  1595.69  1422.05   
13093  100  196 -0.0006 -0.0003  100.0  518.67  643.44  1593.15  1406.82   
13094  100  197 -0.0038  0.0001  100.0  518.67  643.26  1594.99  1419.36   
13095  100  198  0.0013  0.0003  100.0  518.67  642.95  1601.62  1424.99   

          9   ...       18      19    20   21    22     23     24       25  \
0      14.62  ...  8125.55  8.4052  0.03  392  2388  100.0  38.86  23.3735   
1      14.62  ...  8139.62  8.3803  0.03  393  2388  100.0  39.02  23.3916   
2      14.62  ...  8130.10  8.4441  0.03  393  2388  100.0  39.08  23.4166   
3      14.62  ...  8132.90  8.3917  0.03  391  2388  100.0  39.00  23.3737   
4      14.62  ...  8129.54  8.4031  0.03  390  2388  100.0  38.99  23.4130   
...      ...  ...      ...     ...   ...  ...   ...    ...    ...      ...   
13091  14.62  ...  8213.28  8.4715  0.03  394  2388  100.0  38.65  23.1974   
13092  14.62  ...  8210.85  8.4512  0.03  395  2388  100.0  38.57  23.2771   
13093  14.62  ...  8217.24  8.4569  0.03  395  2388  100.0  38.62  23.2051   
13094  14.62  ...  8220.48  8.4711  0.03  395  2388  100.0  38.66  23.2699   
13095  14.62  ...  8214.64  8.4903  0.03  396  2388  100.0  38.70  23.1855   

       26  27  
0     NaN NaN  
1     NaN NaN  
2     NaN NaN  
3     NaN NaN  
4     NaN NaN  
...    ..  ..  
13091 NaN NaN  
13092 NaN NaN  
13093 NaN NaN  
13094 NaN NaN  
13095 NaN NaN  

[13096 rows x 28 columns]

In [47]:
data_train.drop(columns=data_train.columns[-1],  axis=1,  inplace=True)
data_test.drop(columns=data_train.columns[-1],  axis=1,  inplace=True)

In [48]:
data_train.drop(columns=data_train.columns[-1],  axis=1,  inplace=True)
data_test.drop(columns=data_train.columns[-1],  axis=1,  inplace=True)

In [50]:
data_train
data_test

0    1       2       3      4       5       6        7        8   \
0        1    1  0.0023  0.0003  100.0  518.67  643.02  1585.29  1398.21   
1        1    2 -0.0027 -0.0003  100.0  518.67  641.71  1588.45  1395.42   
2        1    3  0.0003  0.0001  100.0  518.67  642.46  1586.94  1401.34   
3        1    4  0.0042  0.0000  100.0  518.67  642.44  1584.12  1406.42   
4        1    5  0.0014  0.0000  100.0  518.67  642.51  1587.19  1401.92   
...    ...  ...     ...     ...    ...     ...     ...      ...      ...   
13091  100  194  0.0049  0.0000  100.0  518.67  643.24  1599.45  1415.79   
13092  100  195 -0.0011 -0.0001  100.0  518.67  643.22  1595.69  1422.05   
13093  100  196 -0.0006 -0.0003  100.0  518.67  643.44  1593.15  1406.82   
13094  100  197 -0.0038  0.0001  100.0  518.67  643.26  1594.99  1419.36   
13095  100  198  0.0013  0.0003  100.0  518.67  642.95  1601.62  1424.99   

          9   ...      16       17       18      19    20   21    22     23  \
0      14.62  ...  521.72  2388.03  8125.55  8.4052  0.03  392  2388  100.0   
1      14.62  ...  522.16  2388.06  8139.62  8.3803  0.03  393  2388  100.0   
2      14.62  ...  521.97  2388.03  8130.10  8.4441  0.03  393  2388  100.0   
3      14.62  ...  521.38  2388.05  8132.90  8.3917  0.03  391  2388  100.0   
4      14.62  ...  522.15  2388.03  8129.54  8.4031  0.03  390  2388  100.0   
...      ...  ...     ...      ...      ...     ...   ...  ...   ...    ...   
13091  14.62  ...  520.69  2388.00  8213.28  8.4715  0.03  394  2388  100.0   
13092  14.62  ...  521.05  2388.09  8210.85  8.4512  0.03  395  2388  100.0   
13093  14.62  ...  521.18  2388.04  8217.24  8.4569  0.03  395  2388  100.0   
13094  14.62  ...  521.33  2388.08  8220.48  8.4711  0.03  395  2388  100.0   
13095  14.62  ...  521.07  2388.05  8214.64  8.4903  0.03  396  2388  100.0   

          24  27  
0      38.86 NaN  
1      39.02 NaN  
2      39.08 NaN  
3      39.00 NaN  
4      38.99 NaN  
...      ...  ..  
13091  38.65 NaN  
13092  38.57 NaN  
13093  38.62 NaN  
13094  38.66 NaN  
13095  38.70 NaN  

[13096 rows x 26 columns]

In [17]:
index_names = ['engine', 'cycle']
setting_names = ['setting_1', 'setting_2', 'setting_3']
sensor_names=[ "(Fan inlet temperature) (◦R)",
"(LPC outlet temperature) (◦R)",
"(HPC outlet temperature) (◦R)",
"(LPT outlet temperature) (◦R)",
"(Fan inlet Pressure) (psia)",
"(bypass-duct pressure) (psia)",
"(HPC outlet pressure) (psia)",
"(Physical fan speed) (rpm)",
"(Physical core speed) (rpm)",
"(Engine pressure ratio(P50/P2)",
"(HPC outlet Static pressure) (psia)",
"(Ratio of fuel flow to Ps30) (pps/psia)",
"(Corrected fan speed) (rpm)",
"(Corrected core speed) (rpm)",
"(Bypass Ratio) ",
"(Burner fuel-air ratio)",
"(Bleed Enthalpy)",
"(Required fan speed)",
"(Required fan conversion speed)",
"(High-pressure turbines Cool air flow)",
"(Low-pressure turbines Cool air flow)" ]
col_names = index_names + setting_names + sensor_names

In [52]:
data_train.columns = col_names
data_train.describe()

data_test.columns = col_names
data_test.describe()

engine         cycle     setting_1     setting_2  setting_3  \
count  13096.000000  13096.000000  13096.000000  13096.000000    13096.0   
mean      51.543907     76.836515     -0.000011      0.000004      100.0   
std       28.289423     53.057749      0.002203      0.000294        0.0   
min        1.000000      1.000000     -0.008200     -0.000600      100.0   
25%       28.000000     33.000000     -0.001500     -0.000200      100.0   
50%       52.000000     69.000000     -0.000000     -0.000000      100.0   
75%       76.000000    113.000000      0.001500      0.000300      100.0   
max      100.000000    303.000000      0.007800      0.000700      100.0   

       (Fan inlet temperature) (◦R)  (LPC outlet temperature) (◦R)  \
count                      13096.00                   13096.000000   
mean                         518.67                     642.475088   
std                            0.00                       0.400899   
min                          518.67                     641.130000   
25%                          518.67                     642.197500   
50%                          518.67                     642.460000   
75%                          518.67                     642.740000   
max                          518.67                     644.300000   

       (HPC outlet temperature) (◦R)  (LPT outlet temperature) (◦R)  \
count                   13096.000000                   13096.000000   
mean                     1588.099204                    1404.735362   
std                         5.003274                       6.688309   
min                      1569.040000                    1384.390000   
25%                      1584.600000                    1399.950000   
50%                      1587.990000                    1404.440000   
75%                      1591.362500                    1409.050000   
max                      1607.550000                    1433.360000   

       (Fan inlet Pressure) (psia)  ...  \
count                 1.309600e+04  ...   
mean                  1.462000e+01  ...   
std                   1.776425e-15  ...   
min                   1.462000e+01  ...   
25%                   1.462000e+01  ...   
50%                   1.462000e+01  ...   
75%                   1.462000e+01  ...   
max                   1.462000e+01  ...   

       (Ratio of fuel flow to Ps30) (pps/psia)  (Corrected fan speed) (rpm)  \
count                             13096.000000                 13096.000000   
mean                                521.747724                  2388.071025   
std                                   0.559627                     0.056934   
min                                 519.380000                  2387.890000   
25%                                 521.380000                  2388.030000   
50%                                 521.780000                  2388.070000   
75%                                 522.150000                  2388.110000   
max                                 523.760000                  2388.320000   

       (Corrected core speed) (rpm)  (Bypass Ratio)   (Burner fuel-air ratio)  \
count                  13096.000000     13096.000000             1.309600e+04   
mean                    8138.947817         8.425844             3.000000e-02   
std                       10.188605         0.029009             1.040874e-17   
min                     8108.500000         8.332800             3.000000e-02   
25%                     8132.310000         8.405600             3.000000e-02   
50%                     8138.390000         8.424900             3.000000e-02   
75%                     8144.360000         8.444300             3.000000e-02   
max                     8220.480000         8.541400             3.000000e-02   

       (Bleed Enthalpy)  (Required fan speed)  \
count      13096.000000               13096.0   
mean         392.571625                2388.0   
std            1.233577                   0.0   
min          389.000000        

In [72]:
# Define a function to calculate the remaining useful life (RUL)
def add_rul(g):
    # Calculate the RUL as the difference between the maximum cycle value and the cycle value for each row
    g['RUL'] = max(g['cycle']) - g['cycle']
    return g

# Apply the add_rul function to the training data grouped by the unit ID
data_train = data_train.groupby('engine').apply(add_rul)
data_test = data_test.groupby('engine').apply(add_rul)

<ipython-input-72-cd8311ac8140>:8: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use 

	>>> .groupby(..., group_keys=True)
  data_train = data_train.groupby('engine').apply(add_rul)
<ipython-input-72-cd8311ac8140>:9: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use 

	>>> .groupby(..., group_keys=True)
  data_test = data_test.groupby('engine').apply(add_rul)


In [54]:
data_train.shape

(20631, 27)

In [73]:
data_train.columns
data_test.columns

Index(['engine', 'cycle', 'setting_1', 'setting_2', 'setting_3',
       '(Fan inlet temperature) (◦R)', '(LPC outlet temperature) (◦R)',
       '(HPC outlet temperature) (◦R)', '(LPT outlet temperature) (◦R)',
       '(Fan inlet Pressure) (psia)', '(bypass-duct pressure) (psia)',
       '(HPC outlet pressure) (psia)', '(Physical fan speed) (rpm)',
       '(Physical core speed) (rpm)', '(Engine pressure ratio(P50/P2)',
       '(HPC outlet Static pressure) (psia)',
       '(Ratio of fuel flow to Ps30) (pps/psia)',
       '(Corrected fan speed) (rpm)', '(Corrected core speed) (rpm)',
       '(Bypass Ratio) ', '(Burner fuel-air ratio)', '(Bleed Enthalpy)',
       '(Required fan speed)', '(Required fan conversion speed)',
       '(High-pressure turbines Cool air flow)',
       '(Low-pressure turbines Cool air flow)', 'RUL'],
      dtype='object')

In [58]:
import torch
from torch import nn

In [60]:
x_train = data_train.iloc[:,0:26]
x_train = torch.Tensor(x_train.to_numpy()).to(device)

In [61]:
y_train = data_train.iloc[:,26:]
y_train = torch.Tensor(y_train.to_numpy()).to(device)

In [75]:
x_test = data_train.iloc[:,0:26]
x_test = torch.Tensor(x_test.to_numpy()).to(device)

y_test = data_train.iloc[:,26:]
y_test = torch.Tensor(y_test.to_numpy()).to(device)

In [27]:
#Model building
#class model_0(nn.Module):
#  def __init__(self):
#      super().__init__()
#      self.linear_layer = nn.Sequential(
#          nn.Linear(in_features= 26,out_features= 100),
#          nn.Linear(in_features= 100,out_features= 200),
#          nn.Linear(in_features= 200,out_features= 1))

#      def forward(self,x:torch.Tensor)->torch.Tensor:
#        return linear_layer(x)

In [64]:
model_0 = nn.Sequential(
          nn.Linear(in_features= 26,out_features= 100),
         #nn.ReLU(),
          nn.Linear(in_features= 100,out_features= 300),
          #nn.ReLU(),
          nn.Linear(in_features = 300,out_features = 500),
          #nn.ReLU(),
          nn.Linear(in_features= 500,out_features= 1)).to(device)

In [65]:
#Set up loss function and optimizer
loss_fn = nn.L1Loss()

optimizer = torch.optim.SGD(params = model_0.parameters(), lr = 0.01)

In [30]:
def accuracy_score(actual, predicted):
 correct = 0
 for i in range(len(actual)):
  if actual[i] == predicted[i]:
    correct += 1
 return correct / float(len(actual)) * 100.0

In [78]:
#Training loop
RANDOM_SEED = 42
torch.manual_seed(42)

epochs = 1000
i = 0
for epoch in range(epochs):
  model_0.train()

  y_pred = model_0(x_train).to(device)
  print(y_pred)

  loss = loss_fn(y_pred,y_train)

  optimizer.zero_grad()

  loss.backward()

  optimizer.step()

  i=i+1

  model_0.eval() #Testing phase

  with torch.inference_mode():
    test_pred = model_0(x_test).to(device)
    #print(test_pred)
    #test_loss = loss_fn(test_pred,y_pred)

  if i%100 == 0:
    acc = accuracy_score(y_test,test_pred)
    print("Accuracy for "+ str(i) + " is " + str(acc))



Streaming output truncated to the last 5000 lines.
        [nan]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[nan],
        [nan],
        [nan],
        ...,
        [nan],
        [nan],
        [nan]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[nan],
        [nan],
        [nan],
        ...,
        [nan],
        [nan],
        [nan]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[nan],
        [nan],
        [nan],
        ...,
        [nan],
        [nan],
        [nan]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[nan],
        [nan],
        [nan],
        ...,
        [nan],
        [nan],
        [nan]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[nan],
        [nan],
        [nan],
        ...,
        [nan],
        [nan],
        [nan]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[nan],
        [nan],
        [nan],
        ...,
        [nan],
        [nan],
        [nan]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([